/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Extract messages from files matching glob patterns (async) */
export declare function extract(patterns: Array<string>, options?: JsExtractOptions | undefined | null): Promise<JsExtractResult>

/** Extract messages from files matching glob patterns (sync) */
export declare function extractSync(patterns: Array<string>, options?: JsExtractOptions | undefined | null): JsExtractResult

/** Extracted message structure for JS */
export interface JsExtractedMessage {
  id: string
  defaultMessage: string
  description?: string
  file?: string
}

/** JavaScript-compatible options for extraction */
export interface JsExtractOptions {
  removePrefix?: string
  moduleSourceName?: string
  separator?: string
  relativeTo?: string
  hashId?: boolean
  hashAlgorithm?: string
  extractSourceLocation?: boolean
  outputMode?: string
}

/** Extract result structure for JS */
export interface JsExtractResult {
  messages: Array<JsExtractedMessage>
  filesProcessed: number
}

/** Parse a single file and extract messages */
export declare function parseFile(filePath: string, options?: JsExtractOptions | undefined | null): Array<JsExtractedMessage>

/**
 * Run CLI with arguments from JS
 * Returns exit code (0 for success, 1 for error)
 */
export declare function runCli(args: Array<string>): number
